version: 2

models:
  - name: submissions
    description: Form D Submissions data cleaned from raw entity data.
    config:
      contract:
        enforced: true
    columns:
      - name: accession_number
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
      - name: file_num
        data_type: string
      - name: filing_datetime
        data_type: datetime
      - name: sic_code
        data_type: string
      - name: schema_version
        data_type: string
      - name: submission_type
        data_type: string
      - name: test_or_live
        data_type: string
      - name: over_100_persons_flag
        data_type: bool
      - name: over_100_issuer_flag
        data_type: bool

sources:
  - name: raw
    loader: bigquery
    database: form-d-project
    schema: raw
    tables:
      - name: issuers
      - name: offerings
      - name: recipients
      - name: related_persons
      - name: signatures
      - name: submissions
