version: 2

models:
  - name: issuers
    description: Form D Issuers data cleaned from raw entity data.
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ['accession_number', 'issuer_seq_key']
    columns:
      - name: accession_number
        data_type: string
        constraints:
          - type: not_null
        tests:
          - unique
      - name: is_primary_issuer_flag
        data_type: bool
      - name: issuer_seq_key
        data_type: string
      - name: cik
        data_type: string
      - name: entity_name
        data_type: string
      - name: street_1
        data_type: string
      - name: street_2
        data_type: string
      - name: city
        data_type: string
      - name: state_or_country
        data_type: string
      - name: state_or_country_description
        data_type: string
      - name: zip_code
        data_type: string
      - name: issuer_phone_number
        data_type: string
      - name: jurisdiction_of_inc
        data_type: string
      - name: issuer_previous_name_1
        data_type: string
      - name: issuer_previous_name_2
        data_type: string
      - name: issuer_previous_name_3
        data_type: string
      - name: edgar_previous_name_1
        data_type: string
      - name: edgar_previous_name_2
        data_type: string
      - name: edgar_previous_name_3
        data_type: string
      - name: entity_type
        data_type: string
      - name: entity_type_other_desc
        data_type: string
      - name: year_of_inc_timespan_choice
        data_type: string
      - name: year_of_inc_value_entered
        data_type: string
  - name: submissions
    description: Form D Submissions data cleaned from raw entity data.
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ['accession_number']
    columns:
      - name: accession_number
        data_type: string
        constraints:
          - type: not_null
        tests:
          - unique
      - name: file_num
        data_type: string
      - name: filing_datetime
        data_type: datetime
      - name: sic_code
        data_type: string
      - name: schema_version
        data_type: string
      - name: submission_type
        data_type: string
      - name: test_or_live
        data_type: string
      - name: over_100_persons_flag
        data_type: bool
      - name: over_100_issuer_flag
        data_type: bool

sources:
  - name: raw
    loader: bigquery
    database: form-d-project
    schema: raw
    tables:
      - name: issuers
      - name: offerings
      - name: recipients
      - name: related_persons
      - name: signatures
      - name: submissions
